# Brewfile — `brew bundle install` 로 일괄 설치
# 이 머신에서 직접 설치한 패키지(brew leaves) 기준. 의존성은 자동 설치됨.

# --- Taps ---
tap "cloudflare/cloudflare"
tap "heroku/brew"
tap "homebrew/services"
tap "manaflow-ai/cmux"
tap "modem-dev/tap"
tap "mongodb/brew"
tap "satococoa/tap"
tap "stablyai/orca"

# --- CLI 도구 ---
brew "cloudflared"
brew "fd"
brew "ffmpeg-full"
brew "fzf"
brew "gh"
brew "git-lfs"
brew "gradle"
brew "heroku"
brew "hunk"
brew "imagemagick-full"
brew "jq"
brew "lazygit"
brew "neovim"
brew "nginx"
brew "nvm"
brew "poppler"
brew "protobuf"
brew "python@3.11"
brew "rbenv"
brew "resvg"
brew "ripgrep"
brew "sevenzip"
brew "tmux"
brew "uv"
brew "xcodegen"
brew "yarn"
brew "yazi"
brew "zoxide"

# --- Casks (기존 brew 설치분) ---
cask "claudebar"
cask "cmux"
cask "font-symbols-only-nerd-font"
cask "gcloud-cli"
cask "hammerspoon"
cask "orca"
cask "tuist"

# --- GUI 앱 (기존에는 수동 설치였던 것 — 새 머신에서는 cask로) ---
cask "arc"
cask "claude"
cask "cursor"
cask "discord"
cask "docker-desktop"
cask "figma"
cask "ghostty"
cask "google-chrome"
cask "intellij-idea-ce"
cask "kakaotalk"
cask "mongodb-compass"
cask "obsidian"
cask "raycast"
cask "slack"
cask "snipaste"
cask "sublime-text"
cask "typora"
cask "visual-studio-code"
cask "zoom"
# cask "alfred"        # 현재 Alfred 4 사용 중 — cask는 최신(5) 설치라 라이선스 확인 후 해제
# cask "perplexity"    # 필요 시 해제
